package com.example.firmaplatformasi.EnumStep;

public enum Huquqlar {
    ADDHODIM,EDITHODIM,DELETEHODIM,BLOCKHODIM,READHODIM,READALLHODIM,
    ADDLAVOZIM,EDITLAVOZIM,DELETELAVOZIM,READLAVOZIM,
    ADDTOPSHIRIQ,DELETETOPSHIRIQ,EDITTOPSHIRIQ,READMYTOPSHIRIQ,READALLTOPSHIRIQ,FINISHTOPSHIRIQ,
    ADDSECTION,EDITSECTION,DELETESECTION,READSECTION
}
